#ifndef LIME_CONFIG_H
#define LIME_CONFIG_H


/* Undef the unwanted from the environment -- eg the compiler command line */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

/* Include the stuff generated by autoconf */
#include "lime_config_internal.h"

/* Prefix everything with LIME_ */
#define LIME_PACKAGE PACKAGE
#define LIME_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#define LIME_PACKAGE_NAME PACKAGE_NAME
#define LIME_PACKAGE_STRING PACKAGE_STRING
#define LIME_PACKAGE_TARNAME PACKAGE_TARNAME
#define LIME_PACKAGE_VERSION PACKAGE_VERSION
#define LIME_VARSION VERSION


/* Undef the unwanted */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION
#endif
